### ISSUE TITLE
Milestone 3 Issue 3: Edit your report literate code document (*.qmd) so that it’s sole job is to narrate your analysis, display your analysis artifacts (i.e., figures and tables), and nicely format the report.

### ISSUE THREAD

**Issue by mikem2m** [UBC-MDS/DSCI522-2425-group24_adult-income-predictor#22]
The goal is that non-data scientists would not be able to tell that code was used to perform your analysis or format your report (i.e., no code should be visible in the rendered report).

You should render your report to either html or PDF. Quarto has all the features needed to make your report satisfy our expectations (bibliography, automatic numbering of figures and tables, inline code rendering, etc). In particular, we expect you to:
- Use markdown headers and Quarto configuration so that a table of contents will be created when the document is rendered.
- Add correctly formatted inline BibTeX references so that a nicely formatted reference list will be present at the end of the document.
- Edit the figure formatting so that Quarto: automatically numbers them, has a label for easy cross referencing, and
controls the figure sizes so the figures are not too big.
- Add a table description argument so that they are automatically numbered by Quarto and use cross referencing to link to the table when it is discussed in the text.
- Edit the narrative so it uses cross-referencing to refer to the figures and tables instead of having their reference hardcode the figure and table numbers.
- Replace any hard-coded values in the Quarto report narrative text with inline Quarto code, so that the text will be automatically updated with the correct value.
- Change the code chunk options so that no code is viewable in the rendered report, just the code outputs where needed (e.g., figures and tables).

**Comment by fraramfra** [comment]
Team,

I've sent out a PR with the first draft of the .qmd file for Issue 3. 

From my perspective only 3 things are missing to complete the milestone:
1- Create the .bib file for the references and include in the report folder
2- Use the .bib reference file to include the references in the narrative of the .qmd file (I put "INSERT REFERECE" comments everywhere I think we need to create a cross reference.
3- (A nice to have, if possible) - If we could save the test score in a csv in the evaluate_model.py so that it could be pulled into the report in the "Model Test Score and Prediction" section, that would be nicer than having the test score hard coded. 

Let me know if you have any questions or comments.

**Comment by mikem2m** [comment]
@QuanhuaHuang-ubc @Calista321 Please finish the remaining work above, as explained by @fraramfra. Thanks!

**Comment by fraramfra** [comment]
Team,

@QuanhuaHuang-ubc @Calista321 @mikem2m 

I've sent out a PR with the bib file and a new version of the .qmd file for Issue 3.

Only 2 things are missing to complete the milestone:
1- (A nice to have, if possible) - If we could save the test score in a csv in the evaluate_model.py so that it could be pulled into the report in the "Model Test Score and Prediction" section, that would be nicer than having the test score hard coded.
2/ Deliver to gradescope for the whole team.

Let me know if you have any questions or comments.

**Comment by mikem2m** [comment]
@fraramfra Looks like the work is completed now. I will close this issue and submit to gradescope! Thanks :)
